### ISSUE TITLE
add a guide to pair programming

### ISSUE THREAD

**Issue by capsulecorplab** [LearnTeachCode/code-coffee-compendium#30]
Add a "tried and true" guide to pair programming in [references](https://github.com/LearnTeachCode/baldwinpark-code-and-coffee#references)

**Comment by TristanDamron** [comment]
Story Points: 1

**Comment by TristanDamron** [comment]
@capsulecorplab What makes a good guide for pair programming? Most of the content I see online only describes what it is, rather than how to do it.

**Comment by capsulecorplab** [comment]
I'm thinking this should actually be a [tutorial](https://documentation.divio.com/tutorials/) for getting started with pair programming, for those who've never pair programmed.

Something like this perhaps? https://tuple.app/pair-programming-guide/your-first-pairing-session
