### ISSUE TITLE
Recategorization of Items

### ISSUE THREAD

**Issue by huynhkimberly** [LearnTeachCode/code-coffee-compendium#52]
Issue was identified that people often don't use the page as preferred source of information RE: common inquiries of "what to learn" and "how to get a job". 

I took a look at the page as someone new to programming with essentially those same questions (I was told many of the intended users are new also). Immediate impression is there is a lot of random stuff - my attention naturally jumps to items that are either a) known to me (eg. python, build a website) or b) speaking to my inner questions (eg. career advice).

AKA site is useful if user already knows what the list items are (source, my programmy hubby saw it and was like "wow this is great"), and/or what they are looking for (which is probably not the intended users' situation). Also, expressing the items in the industry terms may not be as helpful as "how it helps me" or "what it does/achieves".

**Proposal To Alter Content Structure**
I propose you alter the structure of the content to answer the users' immediate questions (either explicit or implicit). Also so that the tangible outcomes of these resources are the first piece of information seen by the user. For example:
1) If I see "learn frameworks", I don't know what a framework is or why I would use it, so it doesn't stick out to me as relevant.
2) But if I see "How do I build a software", and see "learn frameworks" underneath, it is implied that learning frameworks will help me achieve the desired tangible outcome (of making software). 

**Suggestion To Implement With Existing Structure:**
My two cents on how this page could be improved without adding new features/structures:
1. Add a small "How Do I Get A Job" preface section that speaks to some degree about that and how the resources that follow will help to achieve the goal of employment (this was identified as a very common question). You could link this to some external infographics that break down the industry areas (I did some digging and found some and they were extremely helpful to me).
2. Define your main topics in terms of the tangible outcome they will produce, so that I as a noob, can understand more easily (jargon = what). 
3. To help categorize all the items I would ask "why would I learn this/when is this useful?" If the answer is "always" the topic may justify its own section below the higher level topics - they can link down to it. If it is specific to one or two uses, it can be categorized under its respective main topic.

Eg. "How Do I Build A Website"
Subtopic: Content Management Systems
Subtopic: Languages > Ruby > Flask > Django

Eg. "How Do I Create Software"
Subtopic: Open Source
Subtopic: Frameworks
Subtopic: GitHub
Subtopic: Engineering

**Comment by huynhkimberly** [comment]
Side note that I think the page should be simplified wherever possible. Looking at the tables most of the stuff uses browser/internet, which a user probably has given they're on the page in the first place - might make more sense to only make a note of 'special tools required' where applicable.

Tables could be used for subtopic comparison of "subtopic vs. format" on a case by case per main topic

Format examples: Cheat Sheet, Challenge, Lesson/Tutorial, Workshop/Bootcamp, Project

**Comment by huynhkimberly** [comment]
Might be a different project entirely but you could toss up defining things in terms of the job type someone's looking for XD

**Comment by capsulecorplab** [comment]
@huynhkimberly Thanks for opening the issue! I think this is definitely useful feedback. @LearningNerd any follow-up thoughts?
For starters, I'm thinking an FAQ-style list of questions at the top that comment on and point to resources at the bottom via anchor links would be one fix - especially since some resources will have overlapping use cases. The questions themselves can also point to other related questions via anchor links.
@cynful @sugarsyntax @jbazalar @itsevalieu tagging you too, since you're all seasoned co-hosts/organizers

**Comment by capsulecorplab** [comment]
This [PyCon talk](https://youtu.be/t4vKPhjcMZg) outlined 4 categories that all technical documentation should strive to distinguish:
1) Tutorials
2) How-to guides
3) Discussions
4) References

Reorganizing the existing structure into these 4 categories would probably go a long way.

**Comment by capsulecorplab** [comment]
Closing this issue, as per #54
