### ISSUE TITLE
Sitemap diagram is not loading 

### ISSUE THREAD

**Issue by TristanDamron** [LearnTeachCode/code-coffee-compendium#60]
Title says it all. 

Asciidoctor-diagram is throwing a PlantUML syntax error, but I'm not totally sure why. The generated PlantUML code is totally valid.

**Comment by cynful** [comment]
I’m not too familiar with asciidoctor. Bu maybe order of operations matter?  Ie. maybe that diagram and page need to be generated last?

**Comment by TristanDamron** [comment]
That's what I'm thinking too! I've got a couple of ideas that I'll be able to try out later this evening.
