### ISSUE TITLE
Change branch "main" to "master"

### ISSUE THREAD

**Issue by TristanDamron** [LearnTeachCode/code-coffee-compendium#75]
https://thenextweb.com/news/github-plans-to-replace-racially-insensitive-terms-like-master-and-whitelist

LTC strives to be a welcoming, inclusive place for its members. We should change the name of our primary branch on this repository from "master" to "main" and copyedit any terms on the site that may be microaggressions for our community members.

**Comment by capsulecorplab** [comment]
Done
