### ISSUE TITLE
Update instructions for viewing the site locally

### ISSUE THREAD

**Issue by capsulecorplab** [LearnTeachCode/code-coffee-compendium#81]
Content in [Viewing the site locally](https://github.com/LearnTeachCode/code-coffee-compendium/blob/main/README.adoc#viewing-the-site-locally) should be updated with command line instructions for cloning and running docker via the `build.sh` and `serve.sh` bash scripts (e.g., https://github.com/tetrabiodistributed/papra#running-the-website-locally)

**Comment by TristanDamron** [comment]
Story Points: 1

**Comment by TristanDamron** [comment]
Copy from https://github.com/capsulecorplab

**Comment by TristanDamron** [comment]
#69
