### ISSUE TITLE
Update site theme to Cupper

### ISSUE THREAD

**Issue by TristanDamron** [LearnTeachCode/code-coffee-compendium#86]
https://themes.gohugo.io/themes/cupper-hugo-theme/

**Comment by TristanDamron** [comment]
Story Points: 1

**Comment by TristanDamron** [comment]
Acceptance Criteria:
- Site should load properly
- Existing content should be accessible

**Comment by capsulecorplab** [comment]
Before we settle on a theme, it might be worth while conducting a tradestudy on the candidate themes

**Comment by capsulecorplab** [comment]
Asciidoc not rendering properly on Cupper

**Comment by capsulecorplab** [comment]
Also, theme doesn't include an **Edit** button. I think we need a checklist of what features we need in a theme, before settling on a new theme
