### ISSUE TITLE
Identify requirements for a theme

### ISSUE THREAD

**Issue by capsulecorplab** [LearnTeachCode/code-coffee-compendium#88]
This issue entails identifying requirements for a theme. The following is a trade-study of candidate themes, based on the following criteria

| Criteria | Vanilla [Asciidoctor](https://asciidoctor.org) | [Docsy](https://www.docsy.dev/) (Hugo) | [Asciidocsy](https://github.com/DocOps/asciidocsy-jekyll-theme) (Jekyll) |
| ---------- | - | - | - |
| Navigation bar | x | x | x |
| Named anchors | x | x | x |
| Edit button  |    | x | x |
| "Open an issue" button  |    | x | x |
| Asciidoc support | x | x | x |
| Git info |   | x | [Coming soon](https://github.com/DocOps/asciidocsy-jekyll-theme/issues/74) |
| Darkmode |   |   | [Coming soon](https://github.com/DocOps/asciidocsy-jekyll-theme/issues/35) |
| Dynamic search field |   |   | x |

**Comment by capsulecorplab** [comment]
@TristanDamron @cynful @sugarsyntax thoughts?

**Comment by TristanDamron** [comment]
@capsulecorplab Can we close this since we settled on Asciidocsy?

**Comment by capsulecorplab** [comment]
Closing, as per #100
